"""empty message

Revision ID: 0cdbcffd3e91
Revises: 112892f94177
Create Date: 2019-01-05 11:37:27.890352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdbcffd3e91'
down_revision = '112892f94177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('name', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'devices', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'name')
    # ### end Alembic commands ###
