"""scripts table

Revision ID: 112892f94177
Revises: d2d64fefe68c
Create Date: 2018-12-13 20:43:12.105213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112892f94177'
down_revision = 'd2d64fefe68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('prev_state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_type'), 'scripts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_type'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
