"""empty message

Revision ID: 641b6bd86557
Revises: 0cdbcffd3e91
Create Date: 2019-03-10 18:20:34.473042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b6bd86557'
down_revision = '0cdbcffd3e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_name', sa.String(length=20), nullable=True),
    sa.Column('on_hour', sa.Integer(), nullable=True),
    sa.Column('on_minute', sa.Integer(), nullable=True),
    sa.Column('off_hour', sa.Integer(), nullable=True),
    sa.Column('off_minute', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_dev_name'), 'timer', ['dev_name'], unique=False)
    op.create_index(op.f('ix_timer_off_hour'), 'timer', ['off_hour'], unique=False)
    op.create_index(op.f('ix_timer_off_minute'), 'timer', ['off_minute'], unique=False)
    op.create_index(op.f('ix_timer_on_hour'), 'timer', ['on_hour'], unique=False)
    op.create_index(op.f('ix_timer_on_minute'), 'timer', ['on_minute'], unique=False)
    op.drop_index('ix_scripts_type', table_name='scripts')
    op.drop_table('scripts')
    op.add_column('devices', sa.Column('dev_name', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'devices', ['dev_name'])
    op.drop_column('devices', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'dev_name')
    op.create_table('scripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('state', sa.BOOLEAN(), nullable=True),
    sa.Column('prev_state', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('prev_state IN (0, 1)'),
    sa.CheckConstraint('state IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scripts_type', 'scripts', ['type'], unique=False)
    op.drop_index(op.f('ix_timer_on_minute'), table_name='timer')
    op.drop_index(op.f('ix_timer_on_hour'), table_name='timer')
    op.drop_index(op.f('ix_timer_off_minute'), table_name='timer')
    op.drop_index(op.f('ix_timer_off_hour'), table_name='timer')
    op.drop_index(op.f('ix_timer_dev_name'), table_name='timer')
    op.drop_table('timer')
    # ### end Alembic commands ###
