"""devices table

Revision ID: d2d64fefe68c
Revises: 
Create Date: 2018-12-11 19:55:52.766703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d64fefe68c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('prev_state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_dev_id'), 'devices', ['dev_id'], unique=True)
    op.create_index(op.f('ix_devices_type'), 'devices', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_dev_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
